version: 2.1

jobs:
  plan-apply:
    working_directory: /tmp/project
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: "Terraform Init & Plan"
          command: |
            terraform init -input=false
            terraform plan -out=tfapply
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .

  apply:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: "Terraform Apply"
          command: |
            cd /tmp/project
            terraform apply -auto-approve tfapply
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .

  plan-destroy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: "Terraform Plan for Destroy"
          command: |
            cd /tmp/project
            terraform plan -destroy -out=tfdestroy
      - persist_to_workspace:
          root: /tmp/project
          paths:
            - .

  destroy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - attach_workspace:
          at: /tmp/project
      - run:
          name: "Terraform Destroy"
          command: |
            cd /tmp/project
            terraform apply -auto-approve tfdestroy

workflows:
  version: 2
  terraform-workflow:
    jobs:
      - plan-apply
      - hold-apply:
          type: approval
          requires:
            - plan-apply
      - apply:
          requires:
            - hold-apply
      - plan-destroy:
          requires:
            - apply
      - hold-destroy:
          type: approval
          requires:
            - plan-destroy
      - destroy:
          requires:
            - hold-destroy
