version: 2.1
parameters:
  DO_DESTROY:
    type: boolean
    default: false
jobs:
  terraform-job:
    docker:
      # Using a Docker image with Terraform installed (e.g., CircleCI's Terraform image or a custom one).
      - image: hashicorp/terraform:latest
    steps:

      - checkout

      # Terraform init step
      - run:
          name: "Terraform Init"
          command: terraform init

      # Conditionally run Terraform apply or destroy based on the DO_DESTROY environment variable
      - run:
          name: "Terraform Plan or Apply/Destroy"
          command: |
              echo "Running terraform destroy..."
              terraform destroy --auto-approve


workflows:
  terraform-workflow:
    jobs:
      - terraform-job:
          context: my-aws-context # Use a CircleCI context to provide AWS credentials securely
          filters:
            branches:
              only: circleci-project-setup
